# Generated by Django 5.2.8 on 2025-11-19 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['name'], name='catalog_pro_name_2a564d_idx'),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['category'], name='catalog_pro_categor_6ba418_idx'),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['difficulty'], name='catalog_pro_difficu_d5d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['status'], name='catalog_pro_status_07f88b_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['is_public', 'task'], name='catalog_sol_is_publ_f7d773_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['user'], name='catalog_sol_user_id_827736_idx'),
        ),
    ]
