# Generated by Django 5.2.8 on 2025-11-19 17:17

from django.db import migrations


def seed_initial_data(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Difficulty = apps.get_model('catalog', 'Difficulty')

    categories = [
        {
            'name': 'Arrays',
            'description': 'Задачи на работу с массивами и списками',
        },
        {
            'name': 'Strings',
            'description': 'Задачи на работу со строками',
        },
        {
            'name': 'Linked Lists',
            'description': 'Задачи на работу со связными списками',
        },
        {
            'name': 'Trees',
            'description': 'Задачи на работу с деревьями (бинарные, BST и т.д.)',
        },
        {
            'name': 'Graphs',
            'description': 'Задачи на работу с графами',
        },
        {
            'name': 'Dynamic Programming',
            'description': 'Задачи на динамическое программирование',
        },
        {
            'name': 'Sorting',
            'description': 'Задачи на сортировку данных',
        },
        {
            'name': 'Searching',
            'description': 'Задачи на поиск элементов',
        },
        {
            'name': 'Math',
            'description': 'Математические задачи',
        },
        {
            'name': 'Greedy',
            'description': 'Задачи на жадные алгоритмы',
        },
        {
            'name': 'Backtracking',
            'description': 'Задачи на backtracking алгоритмы',
        },
        {
            'name': 'Bit Manipulation',
            'description': 'Задачи на работу с битами',
        },
        {
            'name': 'Hash Tables',
            'description': 'Задачи на работу с хеш-таблицами',
        },
        {
            'name': 'Stack',
            'description': 'Задачи на работу со стеком',
        },
        {
            'name': 'Queue',
            'description': 'Задачи на работу с очередью',
        },
        {
            'name': 'Heap',
            'description': 'Задачи на работу с кучей (heap)',
        },
        {
            'name': 'Binary Search',
            'description': 'Задачи на бинарный поиск',
        },
        {
            'name': 'Two Pointers',
            'description': 'Задачи на технику двух указателей',
        },
        {
            'name': 'Sliding Window',
            'description': 'Задачи на технику скользящего окна',
        },
        {
            'name': 'Divide and Conquer',
            'description': 'Задачи на разделяй и властвуй',
        },
        {
            'name': 'Recursion',
            'description': 'Задачи на рекурсию',
        },
    ]

    difficulties = [
        {'name': 'Easy'},
        {'name': 'Medium'},
        {'name': 'Hard'},
    ]

    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']},
        )

    for difficulty_data in difficulties:
        Difficulty.objects.get_or_create(name=difficulty_data['name'])


def reverse_seed_initial_data(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Difficulty = apps.get_model('catalog', 'Difficulty')

    category_names = [
        'Arrays', 'Strings', 'Linked Lists', 'Trees', 'Graphs',
        'Dynamic Programming', 'Sorting', 'Searching', 'Math', 'Greedy',
        'Backtracking', 'Bit Manipulation', 'Hash Tables', 'Stack', 'Queue',
        'Heap', 'Binary Search', 'Two Pointers', 'Sliding Window',
        'Divide and Conquer', 'Recursion',
    ]

    difficulty_names = ['Easy', 'Medium', 'Hard']

    Category.objects.filter(name__in=category_names).delete()
    Difficulty.objects.filter(name__in=difficulty_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_programmingtask_catalog_pro_name_2a564d_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            seed_initial_data, reverse_seed_initial_data
        ),
    ]
