# Generated by Django 5.2.8 on 2025-12-23 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_programming_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['added_by'], name='catalog_pro_added_b_8c5ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['status', 'category'], name='catalog_pro_status_2130ad_idx'),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['status', 'difficulty'], name='catalog_pro_status_6fadf6_idx'),
        ),
        migrations.AddIndex(
            model_name='programmingtask',
            index=models.Index(fields=['created_at'], name='catalog_pro_created_9f31f6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['solution'], name='catalog_rev_solutio_8ad9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['added_by'], name='catalog_rev_added_b_3b74a5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='catalog_rev_created_05b149_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['is_public'], name='catalog_sol_is_publ_13df67_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['task'], name='catalog_sol_task_id_3ca359_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['language'], name='catalog_sol_languag_419090_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['created_at'], name='catalog_sol_created_86417e_idx'),
        ),
    ]
